importScripts(
  'model-registry.js',
  'settings/settings.js',
  'core/retry.js',
  'core/prompts.js',
  'core/errors.js',
  'core/telemetry.js',
  'providers/utils.js',
  'providers/gemini.js',
  'providers/openai.js',
  'providers/claude.js',
  'providers/openrouter.js',
  'providers/ollama.js',
  'core/router.js',
  'messaging/messageHandler.js'
);
